server:
  port: 8765

spring:
  application:
    name: service-feign

#服务注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    #开启断路器
    enabled: true