server:
  port: 8761

spring:
  application:
    name: eurka-server

eureka:
  server:
    #Eureka自我保护机制，默认打开状态，建议生产环境打开此配置。
    #测试时关闭自我保护机制，保证不可用服务及时被踢出
    enable-self-preservation: false
    #清理间隔（单位毫秒，默认是60*1000）
    eviction-interval-timer-in-ms: 4000
  instance:
    hostname: localhost
  client:
    #是否注册自身到eureka服务器（没必要注册自身，所以这里是false）
    registerWithEureka: false
    #是否从eureka服务器获取注册信息（没必要获取自身，所以这里是false）
    fetchRegistry: false
    serviceUrl:
      #设置eureka服务器所在的地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


